services:
  web:
    build: .
    container_name: dataecon_web
    ports:
      - "5000:10000"
    volumes:
      - ./app:/app
      - ./app/data:/app/data
    environment:
      - DATABASE_URL=postgresql://dataecon:dataecon123@db:5432/dataecon
      - SECRET_KEY=e0dcf3318668ef9c17aabdbcb5ba041d76b01e97c13567f6a24de8686c9a3411
    depends_on:
      - db
    networks:
      - dataecon_network

  db:
    image: postgres:15
    container_name: dataecon_db
    environment:
      - POSTGRES_USER=dataecon
      - POSTGRES_PASSWORD=dataecon123
      - POSTGRES_DB=dataecon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dataecon_network

volumes:
  postgres_data:

networks:
  dataecon_network:
